---
#
# edX Analytics Configuration
#
# github:     https://github.com/openedx/analytics-configuration
# license:    https://github.com/openedx/analytics-configuration/blob/master/LICENSE
# code style: https://github.com/openedx/configuration/wiki/Ansible-Coding-Conventions
##
# Vars for role user
#


#
# vars are namespace with the module name.
#
user_role_name: user

# override this var to add a prefix to the prompt
# also need to set comment_update_bashrc for to
# update the system bashrc default
USER_CMD_PROMPT: ""

# these are the default links to create in the
# restricted user's ~/bin directory
# defaults to sudo, more can be added by overriding
# this var
user_rbash_links:
  - /usr/bin/sudo

# parameter for this role,
# must be set when called and should NOT
# be set in extra vars since it
# will take precedence over the paramter
user_info: []
